version: '2'
services:
  app:
    build: .
    restart: always
    environment:
      VIRTUAL_HOST: trustedaf.poma.in
      LETSENCRYPT_HOST: trustedaf.poma.in
      nginx_client_max_body_size: 50m
      MYSQL_HOST: mysql
    env_file: .env
    volumes:
      - /data/powers/verify_contribution:/app/verify_contribution

  mysql:
    image: mysql:5.7
    restart: always
    env_file: .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

networks:
  default:
    external:
      name: frontend_default